[general]
import = [
    "~/.config/alacritty/themes/rose_pine.toml"
]

[font]
size = 16

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "None"
opacity = 0.91
startup_mode = "Maximized"
resize_increments = true

[window.padding]
x = 0
y = 0

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "F", mods = "Control|Shift", mode = "AppCursor", action = "ToggleFullScreen" }
]

[selection]
save_to_clipboard = true

[terminal]
shell = { program = "/usr/bin/bash", args = ["-l"] }
